#notes to self
  #depends_on   -> start services in the right order
  #networks     -> isolated communication between services
  #volumes      -> persist data and share between services
  #environment  -> configure services with env variables -> probably reads from the .env file


# Container definitions
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    networks:
      - oneiro_web
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
      - wordpress_db:/var/lib/mysql
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=mariadb
    secrets:
      - db_password
      - wp_admin_password
    depends_on:
      - mariadb
    networks:
      - oneiro_web
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MARIADB_ROOT_PASSWORD_FILE=run/secrets/db_root_password
      - MARIADB_PASSWORD_FILE=run/secrets/db_password
    secrets:
      - db_password
      - db_root_password
    networks:
      - oneiro_web
    restart: always

volumes:
  wordpress_files:
    name: wordpress_files
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress_files
      o: bind
  wordpress_db:
    name: wordpress_db
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress_db
      o: bind

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt

networks:
  oneiro_web:
    driver: bridge

