#notes to self
  #depends_on   -> start services in the right order
  #networks     -> isolated communication between services
  #volumes      -> persist data and share between services
  #environment  -> configure services with env variables -> probably reads from the .env file

  #docker compose up    -> to start
  #docker compose down  -> to stop






services:                   #sample seen from some website.
  nginx:
    #probably smth to do with the service

  wordpress:

